apiVersion: apps/v1
kind: Deployment
metadata:
  name: sens-ai
  labels:
    app: sens-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sens-ai
  template:
    metadata:
      labels:
        app: sens-ai
    spec:
      containers:
      - name: sens-ai
        image: vishal28d/sens-ai
        ports:
        - containerPort: 3100
        env:
        - name: PORT
          value: "3100"
